import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer'
import { weightDisplay, formatPdfDate } from '../../utils/pdfUtils'

const NAVY = '#1E2D3D'
const TEAL = '#29B5CC'
const TEAL_LIGHT = '#E1F5FA'
const GREY = '#6B7280'
const BORDER = '#D4E8E8'

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 11,
    color: NAVY,
    paddingTop: 48,
    paddingBottom: 48,
    paddingHorizontal: 48,
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: TEAL,
    paddingBottom: 12,
  },
  subtitle: {
    fontSize: 9,
    color: GREY,
    letterSpacing: 1.5,
    marginTop: 2,
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  logoBar: {
    width: 3,
    height: 20,
    backgroundColor: TEAL,
    borderRadius: 2,
    marginRight: 8,
  },
  logoManual: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 16,
    color: NAVY,
  },
  logoRx: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 16,
    color: TEAL,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    fontSize: 10,
    color: GREY,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 8,
  },
  sectionName: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 13,
    color: NAVY,
    marginRight: 8,
  },
  sectionFreq: {
    fontSize: 9,
    color: TEAL,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: BORDER,
    marginBottom: 16,
    marginTop: 8,
  },
  exerciseBlock: {
    marginBottom: 14,
  },
  exerciseTitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 12,
    color: NAVY,
    marginBottom: 3,
  },
  exerciseMeta: {
    fontSize: 10,
    color: GREY,
    marginBottom: 4,
  },
  notesBox: {
    backgroundColor: TEAL_LIGHT,
    borderRadius: 4,
    borderLeftWidth: 2,
    borderLeftColor: TEAL,
    padding: 6,
    marginTop: 4,
  },
  notesText: {
    fontSize: 10,
    color: NAVY,
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 48,
    right: 48,
    textAlign: 'center',
    fontSize: 8,
    color: GREY,
  },
})

export function AllSessionsPDF({ clinicName, clientName, prescriptions, weightUnit }) {
  const today = formatPdfDate(new Date())

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View style={styles.logoRow}>
            <View style={styles.logoBar} />
            <Text style={styles.logoManual}>
              Manual<Text style={styles.logoRx}>Rx</Text>
            </Text>
          </View>
          <Text style={styles.subtitle}>EXERCISE PROGRAM — {clinicName}</Text>
        </View>

        <View style={styles.metaRow}>
          <Text>Client: {clientName}</Text>
          <Text>Date: {today}</Text>
        </View>

        {prescriptions.map((presc, pi) => (
          <View key={pi}>
            <View style={styles.sectionHeader}>
              <Text style={styles.sectionName}>{presc.name}</Text>
              <Text style={styles.sectionFreq}>{presc.frequencyLabel}</Text>
            </View>
            {presc.exercises.map((ex, ei) => (
              <View key={ei} style={styles.exerciseBlock}>
                <Text style={styles.exerciseTitle}>{ei + 1}. {ex.name}</Text>
                <Text style={styles.exerciseMeta}>
                  {ex.sets} sets × {ex.reps} {ex.measurement_type === 'seconds' ? 'sec' : 'reps'}
                  {ex.weight ? ` @ ${weightDisplay(ex.weight, weightUnit)}` : ' — Bodyweight'}
                  {ex.bilateral ? ' — Both sides' : ''}
                </Text>
                {ex.therapist_notes ? (
                  <View style={styles.notesBox}>
                    <Text style={styles.notesText}>{ex.therapist_notes}</Text>
                  </View>
                ) : null}
              </View>
            ))}
            {pi < prescriptions.length - 1 && <View style={styles.divider} />}
          </View>
        ))}

        <Text style={styles.footer}>Generated by ManualRx</Text>
      </Page>
    </Document>
  )
}
