import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer'
import { formatPdfDate } from '../../utils/pdfUtils'
import { formatTempo } from '../../utils/formatTempo'
import { ExerciseTablePDF } from './ExerciseTablePDF'

const NAVY = '#1E2D3D'
const TEAL = '#29B5CC'
const TEAL_LIGHT = '#E8F9FC'
const TEAL_BORDER = '#A8E6F0'
const GREY = '#6B7280'

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 11,
    color: NAVY,
    paddingTop: 48,
    paddingBottom: 48,
    paddingHorizontal: 48,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    borderBottomWidth: 2.5,
    borderBottomColor: TEAL,
    paddingBottom: 10,
    marginBottom: 12,
  },
  logoManual: { fontFamily: 'Helvetica-Bold', fontSize: 18, color: NAVY },
  logoRx: { fontFamily: 'Helvetica-Bold', fontSize: 18, color: TEAL },
  subtitle: { fontSize: 8, color: GREY, letterSpacing: 2, marginTop: 3 },
  headerRight: { textAlign: 'right' },
  headerClinic: { fontSize: 9, fontFamily: 'Helvetica-Bold', color: NAVY },
  headerDate: { fontSize: 8, color: GREY, marginTop: 1 },
  metaStrip: {
    flexDirection: 'row',
    backgroundColor: TEAL_LIGHT,
    borderWidth: 1,
    borderColor: TEAL_BORDER,
    borderRadius: 6,
    padding: 8,
    marginBottom: 14,
  },
  metaItem: { flexDirection: 'column', marginRight: 20 },
  metaLabel: { fontSize: 7.5, fontFamily: 'Helvetica-Bold', color: TEAL, marginBottom: 1 },
  metaValue: { fontSize: 9.5, fontFamily: 'Helvetica-Bold', color: NAVY },
  tempoNote: {
    fontSize: 8, color: GREY, marginTop: 16,
    borderTopWidth: 1, borderTopColor: TEAL_BORDER, paddingTop: 8,
  },
  footer: {
    position: 'absolute', bottom: 24, left: 48, right: 48,
    flexDirection: 'row', justifyContent: 'space-between',
  },
  footerText: { fontSize: 7, color: GREY },
})

export function PrescriptionPDF({ clinicName, clientName, prescriptionName, exercises, weightUnit, frequencyLabel }) {
  const today = formatPdfDate(new Date())
  const hasTempoEx = exercises.some(e =>
    formatTempo(e.tempo_eccentric, e.tempo_bottom_pause, e.tempo_concentric, e.tempo_top_pause) != null
  )

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.logoManual}>Manual<Text style={styles.logoRx}>Rx</Text></Text>
            <Text style={styles.subtitle}>EXERCISE PROGRAM</Text>
          </View>
          <View style={styles.headerRight}>
            <Text style={styles.headerClinic}>{clinicName}</Text>
            <Text style={styles.headerDate}>{today}</Text>
          </View>
        </View>

        <View style={styles.metaStrip}>
          <View style={styles.metaItem}>
            <Text style={styles.metaLabel}>CLIENT</Text>
            <Text style={styles.metaValue}>{clientName}</Text>
          </View>
          <View style={styles.metaItem}>
            <Text style={styles.metaLabel}>SESSION</Text>
            <Text style={styles.metaValue}>{prescriptionName}</Text>
          </View>
          {frequencyLabel ? (
            <View style={styles.metaItem}>
              <Text style={styles.metaLabel}>FREQUENCY</Text>
              <Text style={styles.metaValue}>{frequencyLabel}</Text>
            </View>
          ) : null}
        </View>

        <ExerciseTablePDF exercises={exercises} weightUnit={weightUnit} />

        {hasTempoEx && (
          <Text style={styles.tempoNote}>
            * Tempo (seconds): Eccentric — Bottom Pause — Concentric — Top Pause
          </Text>
        )}

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Generated by ManualRx</Text>
          <Text style={styles.footerText} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>
    </Document>
  )
}
