import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer'
import { formatPdfDate } from '../../utils/pdfUtils'
import { frequencyLabel } from '../../utils/frequencyUtils'
import { ExerciseTablePDF } from './ExerciseTablePDF'

const NAVY = '#1E2D3D'
const TEAL = '#29B5CC'
const TEAL_LIGHT = '#E8F9FC'
const TEAL_BORDER = '#A8E6F0'
const GREY = '#6B7280'

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 11,
    color: NAVY,
    paddingTop: 48,
    paddingBottom: 48,
    paddingHorizontal: 48,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    borderBottomWidth: 2.5,
    borderBottomColor: TEAL,
    paddingBottom: 10,
    marginBottom: 12,
  },
  logoManual: { fontFamily: 'Helvetica-Bold', fontSize: 18, color: NAVY },
  logoRx: { fontFamily: 'Helvetica-Bold', fontSize: 18, color: TEAL },
  subtitle: { fontSize: 8, color: GREY, letterSpacing: 2, marginTop: 3 },
  headerRight: { textAlign: 'right' },
  headerClinic: { fontSize: 9, fontFamily: 'Helvetica-Bold', color: NAVY },
  headerDate: { fontSize: 8, color: GREY, marginTop: 1 },
  programMeta: { marginBottom: 16 },
  programTitle: { fontFamily: 'Helvetica-Bold', fontSize: 15, color: NAVY, marginBottom: 3 },
  programSubtitle: { fontSize: 8, color: GREY },
  weekBlock: { marginBottom: 18 },
  weekHeaderRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  weekBadge: {
    backgroundColor: TEAL, borderRadius: 4,
    paddingVertical: 4, paddingHorizontal: 10,
    marginRight: 8,
  },
  weekBadgeText: { color: '#FFFFFF', fontSize: 8, fontFamily: 'Helvetica-Bold' },
  weekRule: { flex: 1, height: 1, backgroundColor: TEAL_BORDER },
  sessionBlock: {
    marginBottom: 10,
    paddingLeft: 10,
    borderLeftWidth: 3,
    borderLeftColor: TEAL,
  },
  sessionHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 6,
  },
  sessionName: { fontFamily: 'Helvetica-Bold', fontSize: 10, color: NAVY, marginRight: 6 },
  sessionFreq: { fontSize: 7.5, color: TEAL },
  tempoNote: {
    fontSize: 8, color: GREY, marginTop: 16,
    borderTopWidth: 1, borderTopColor: TEAL_BORDER, paddingTop: 8,
  },
  footer: {
    position: 'absolute', bottom: 24, left: 48, right: 48,
    flexDirection: 'row', justifyContent: 'space-between',
  },
  footerText: { fontSize: 7, color: GREY },
})

// frequencyLabel imported from frequencyUtils — handles null → 'No repeat', 1 → 'Daily', 7 → 'Weekly'

export function ProgramPDF({ clinicName, clientName, programName, startDate, weeks, weightUnit }) {
  const today = formatPdfDate(new Date())
  const hasTempoEx = weeks.some(w =>
    w.sessions.some(s => s.exercises.some(e => e.tempo_eccentric != null))
  )

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.logoManual}>Manual<Text style={styles.logoRx}>Rx</Text></Text>
            <Text style={styles.subtitle}>EXERCISE PROGRAM</Text>
          </View>
          <View style={styles.headerRight}>
            <Text style={styles.headerClinic}>{clinicName}</Text>
            <Text style={styles.headerDate}>{today}</Text>
          </View>
        </View>

        <View style={styles.programMeta}>
          <Text style={styles.programTitle}>{programName}</Text>
          <Text style={styles.programSubtitle}>
            {`Client: ${clientName}`}
            {startDate ? ` · Start: ${formatPdfDate(new Date(startDate))}` : ''}
            {weeks.length > 0 ? ` · Duration: ${weeks.length} week${weeks.length !== 1 ? 's' : ''}` : ''}
          </Text>
        </View>

        {weeks.map((week, wi) => (
          <View key={wi} style={styles.weekBlock}>
            <View style={styles.weekHeaderRow}>
              <View style={styles.weekBadge}>
                <Text style={styles.weekBadgeText}>WEEK {week.weekNumber}</Text>
              </View>
              <View style={styles.weekRule} />
            </View>

            {week.sessions.map((session, si) => (
              <View key={si} style={styles.sessionBlock}>
                <View style={styles.sessionHeader}>
                  <Text style={styles.sessionName}>{session.name}</Text>
                  {session.frequencyDays
                    ? <Text style={styles.sessionFreq}>{frequencyLabel(session.frequencyDays)}</Text>
                    : null
                  }
                </View>
                <ExerciseTablePDF exercises={session.exercises} weightUnit={weightUnit} />
              </View>
            ))}
          </View>
        ))}

        {hasTempoEx && (
          <Text style={styles.tempoNote}>
            * Tempo (seconds): Eccentric — Bottom Pause — Concentric — Top Pause
          </Text>
        )}

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Generated by ManualRx</Text>
          <Text style={styles.footerText} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>
    </Document>
  )
}
